- config/README.rst
- config/config-package.py
This help during development, debugging and in case of non-trivial changes.
> Add cli option to prevent direct vcs push.

- config/README.rst
> Fix ReST indentation, single backticks, and a typo

- config/pure-python-without-pypy/MANIFEST.in
- config/pure-python-without-pypy/gitignore
- config/pure-python/gitignore
- config/pure-python/setup.cfg
- config/pure-python/tox.ini
I don't see why "without-pypy" implies it won't have Sphinx
documentation, or why the "with-pypy" config is not capable of enforcing
coverage thresholds.  Or why .meta.cfg files should not be ignored by
check-manifest in "with-pypy" configs.
These seem like accidental differences introduced by changing one or the
other config while forgetting the other one exists.
I also snuck in a .gitignore for .coverage.*, because people (and
projects) sometimes use coverage in parallel mode.
> Fix differences between the two configurations

- config/buildout-recipe/tox.ini.j2
- config/default/tox-docs.j2
- config/default/tox-envlist.j2
- config/default/tox-lint.j2
- config/default/tox-testenv.j2
- config/pure-python/tox.ini.j2
This makes it easier to make changes and to introduce new config types later on.
> Re-use snippets for tox.ini via include.

- config/default/gitignore
This directory shows up when setuptools has to download some packages itself, usually because of setup_requires.
Because I currently have a log of junk show up in ~/src/zopefoundation/zope.app.publication/.eggs/, and I see that its .gitignore says
```
```
> Ignore .eggs/

- config/default/appveyor.yml.j2
This appears to be necessary for at least zope.sendmail on Python 3.9,
where (due to lack of binary Windows wheels of zope.proxy for 3.9) pip
install fails to build and install zope.proxy from sources if wheel is
not available.
(I think this is due to a new pip version?  Because older pips used to
fall back to setup.py install if setup.py bdist_wheel failed.)
> pip install wheel in Appveyor builds

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
- config/pure-python/packages.txt
This is needed for https://github.com/zopefoundation/z3c.layer.ready2go/pull/1
where lxml cloud not be installed on PyPy3 without liblxml and libxslt
dev packages installed.
> Add ability to install additional packages on GHA.

- config/README.rst
- config/buildout-recipe/coveragerc.j2
- config/buildout-recipe/tox.ini.j2
- config/config-package.py
- config/default/gitignore
- config/default/setup.cfg.j2
- config/default/tox-coverage-config.j2
- config/default/tox-docs.j2
- config/default/tox-envlist.j2
- config/default/tox-testenv.j2
- config/pure-python/packages.txt
- config/pure-python/tox.ini.j2
- config/zope-product/packages.txt
- config/zope-product/tox.ini.j2
This means we now support a new type which uses `zc.buildout` to install the package under test.
See https://github.com/zopefoundation/Products.MailHost/pull/39 as an example built with this new type.
> Add support for Zope Product packages.

- config/zope-product/tox.ini.j2
`easy_install` is not supported anymore by setuptools.
> Pin the version of `setuptools` until `zc.buildout = 3.0` is released.

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/pure-python/packages.txt
This includes the ability to run them via GHA.
See https://github.com/zopefoundation/zc.form/pull/7 making use of these changes.
> Add ability to define additional tox environments.

- config/README.rst
- config/config-package.py
- config/default/appveyor.yml.j2
This is the only way which makes sense for https://github.com/zopefoundation/Zope/pull/942.
I did not find another way where it does not break.
> Add option to completely replace the contents of appveyor.yml.

- config/README.rst
- config/config-package.py
- config/default/tox-testenv.j2
Needed for https://github.com/zopefoundation/zope.testrunner/pull/116
where I want to use tox's factors to conditionally enable the 'subunit'
extra for tox environments like py38-subunit.
This is an alternative to #71.
Closes #71.
> Make it possible to configure [testenv] extras

- config/README.rst
I tried both ways and only one worked.
Fixes #67.
> Fix invocation syntax in README

- config/README.rst
- config/config-package.py
Fixes #73 
The code will look for a `tox` script on the current `$PATH` and fall back to the current working directory's `bin` subfolder.
> Look for `tox` on `$PATH` first, then dive into `bin`

- config/README.rst
- config/config-package.py
Fixes #77 
Adds an option `--no-commit` which prevents the `git add` and `git commit` steps (and implies that nothing will be pushed, either). This makes it easier to inspect the changes or re-run the script without causing more and more commits.
> Add option to prevent automatic commits

- config/default/tests.yml.j2
Fixes #74 
This change comes closest to the behavior we had before with Travis while avoiding doubling CI checks on pull requests. It runs CI on all branch pushes and omits a separate CI configuration for PRs, which are already fully covered by CI for pushes to the branches they are based on.
> Run CI on all branch pushes

- config/README.rst
- config/config-package.py
- config/default/setup.cfg.j2
For `Products.Sessions`, which contains two packages, it is necessary to be able to specify the `isort` `known_local_folder` directive.
> Add isort config for known_local_folder

- config/README.rst
- config/buildout-recipe/tox.ini.j2
- config/config-package.py
- config/default/tox-testenv.j2
- config/pure-python/packages.txt
- config/pure-python/tox.ini.j2
The one and only use-case of this is to make zope.testrunner's own
tox.ini not depend on zope.testrunner.  I made it a configurable list
for maximum flexibility, which might be a mistake.
~~I haven't tested this code yet.~~
I have tested this on zope.testrunner and it works the way I expect.
> Introduce testenv-deps option

- config/default/MANIFEST.in.j2
In response to https://github.com/zopefoundation/Products.MIMETools/pull/4#discussion_r595822627
This PR cuts down the number of entries in the `MANIFEST.in` template to the absolute minimum. For example, working with the tool has shown that many Sphinx documentation folders don't bother including a Windows `.bat` file for building, and the only thing that is guaranteed to always exist in a `src` folder is Python files.
With this PR, everything else can be added to the `additional-rules` configuration option in the `.meta.toml` `[manifest]` section.
> Prune list of automatically included file types to prevent warnings

- config/README.rst
- config/config-package.py
- config/default/tox-testenv.j2
- config/zope-product/tox.ini.j2
This is needed for zopefoundation/meta#63 aka support packages with C code
and shown in action at https://github.com/zopefoundation/z3c.recipe.compattest/pull/5/commits/dd5105edc032a1392fbb4588e2554ac7e43acdf2
> Add option to set `setenv`.

- config/default/tox-testenv.j2
Needed for https://github.com/zopefoundation/zope.configuration/pull/54
> Do not run Sphinx doctests on legacy Python as they might fail.

- config/config-package.py
- config/default/tox-coverage-config.j2
This change is needed for https://github.com/zopefoundation/zope.app.publisher/pull/15. Otherwise coverage is 0.
I do not understand why this breaks for this package as all other `pure-python` packages went fine.
> Use package name for coverage source config.

- config/README.rst
- config/buildout-recipe/tox.ini.j2
- config/c-code/coveragerc.j2
- config/c-code/packages.txt
- config/c-code/tests-cache.j2
- config/c-code/tests-download.j2
- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/MANIFEST.in.j2
- config/default/appveyor.yml.j2
- config/default/tox-docs.j2
- config/default/tox-testenv.j2
- config/pure-python/tox.ini.j2
- config/zope-product/tox.ini.j2
Build on example of zope.interface.
See https://github.com/zopefoundation/zope.interface/pull/243
> Add template for packages with c-code.

- config/config-package.py
Currently if you run config-package.py with no arguments, it'll always
set [tox] flake8 = true instead of preserving the existing value.
> Preserve [tox] flake8

- config/config-package.py
- When .meta.toml doesn't exist already, autodetect whether the package uses Sphinx and Appveyor
- Make --with-sphinx an alias for --with-docs
- Warn when .meta.toml has Sphinx doctests enabled without having Sphinx docs enabled, because this is likely a mistake by someone passing --with-sphinx when they wanted --with-docs
> Smarter features

- config/README.rst
- config/c-code/manylinux-install.sh.j2
- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/appveyor.yml.j2
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/default/tox-lint.j2
This PR was used for
* https://github.com/zopefoundation/Missing/pull/8
* https://github.com/zopefoundation/ExtensionClass/pull/35
(I did only try it with the `pure-python` and `c-code` types, yet).
`check-python-versions` is omitted because of https://github.com/mgedmin/check-python-versions/issues/28
> Allow to test against the non-final Python 3.10 version.

- config/c-code/tests.yml.j2
- config/default/tox-docs.j2
- config/default/tox-testenv.j2
- config/pure-python/tox.ini.j2
Problem shifted to Sphinx 5.
Used for https://github.com/zopefoundation/zope.schema/pull/109
> Sphinx 4 got compatible with repoze.sphinx.autointerface again.

- config/README.rst
- config/multi-call.py
- config/re-enable-actions.py
- config/shared/packages.py
- config/shared/path.py
Fixes #88.
I started to use the script but we have to update some of our repositories to get the ability to trigger a workflow manually. (This is already in the the default configuration of `meta/config`, but some repositories where migrated before.)
Open issues:
> Script to re-enable GitHub Actions.

- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
A PyPy never should publish a wheel on PyPI as it cannot be used elsewhere and is not tagged as PyPy only.
Additionally restored that PyPy3 does not run on MacOS. (The version was updated from 3.6 to 3.7 but not the exclude.)
Fixes #128.
> Prevent faulty compiled wheel.

- config/c-code/tests.yml.j2
- config/config-package.py
This change is only necessary for the c-code template.
The other ones already use tox in GHA.
Needed for https://github.com/zopefoundation/zope.container/pull/43
> Run Sphinx doctests only in GHA if the run in tox.

- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
- config/config-package.py
- config/default/tests.yml.j2
Their ABI might not be stable, yet and not compatible across the alpha versions.
Use non-binary coverage version.
They published a wheel not compatible with the current alpha release.
Remove installing coverage in places where it is not needed.
> Do not publish future versions

- CONTRIBUTING.md
- config/README.rst
- config/config-package.py
- config/default/CONTRIBUTING.md
- config/default/MANIFEST.in.j2
- config/pure-python/packages.txt
The file is a raw copy of in https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md
which is not visible enough: It seems only to be referenced in a notice
on the right hand side when creating the first new PR.
See https://github.com/zopefoundation/zodbpickle/pull/64#issuecomment-1026927634 as an example missing the `CONTRIBUTING.md` file.
See https://github.com/zopefoundation/ExtensionClass/pull/41 which was created using this PR.
> Add CONTRIBUTING.md to the root of the target repository

- config/config-package.py
- config/default/tests.yml.j2
* If CONTRIBUTING.md is not added before the lint tox environment runs it complains that there is a file which is not under version control.
* `pypy3` defaults to `pypy-3.6` which no longer seems to be installed on GHA Windows machines.
Needed for https://github.com/zopefoundation/zope.testrunner/pull/128
> Fix CONTRIBUTING.md and PyPy3 usage:

- config/README.rst
- config/buildout-recipe/tox.ini.j2
- config/c-code/packages.txt
- config/c-code/tox.ini.j2
- config/config-package.py
- config/pure-python/tox.ini.j2
- config/zope-product/tox.ini.j2
This is needed for https://github.com/zopefoundation/persistent/pull/169.
> Allow [tox] -> coverage-command to be a list.

- config/README.rst
- config/c-code/manylinux-install.sh.j2
- config/config-package.py
This is needed for https://github.com/zopefoundation/BTrees/pull/178
> Add ability to configure which tests are run on aarch64.

- config/zope-product/tox.ini.j2
This is needed for https://github.com/zopefoundation/Zope/pull/1014.
> Update the zope-product template to zc.buildout 3.x.

- config/pure-python/packages.txt
- config/zope-product/tox.ini.j2
- a current wheel version has to be installed in the first place as otherwise restarting buildout after updating it might fail.
- flake8-html is not compatible with the current version of jinja2 (forcing no flake8 violations make the report obsolete.)
Needed for https://github.com/zopefoundation/Products.MailHost/pull/43
> Fix zope-product template:

- config/zope-product/tox.ini.j2
This is the first version which supports a current setuptools version.
Used in https://github.com/zopefoundation/Products.CMFCore/pull/122
> Update to zc.buildout 3.0.0rc3.

- config/default/gitignore
- config/default/setup.cfg.j2
- config/default/tox-lint.j2
This PR adds `isort` to the linting configuration for `pure-python`. It also adds a log file to `.gitignore` that is created by `zope.testing.loggingsupport`, which is used by ZEO tests.
> Add isort to linting for type pure-python

- config/c-code/tests.yml.j2
- config/config-package.py
- config/default/setup.cfg.j2
- config/default/tox-testenv.j2
This is needed for https://github.com/zopefoundation/AccessControl/pull/126.
Additionally I had to use `3.11.0-alpha.6` as a7 is not yet on GHA.
> Allow to use pre-release versions when using future python versions.

- config/buildout-recipe/coveragerc.j2
- config/config-package.py
- config/default/tests.yml.j2
- config/default/tox-coverage-config.j2
- config/pure-python/tox.ini.j2
- config/zope-product/tox.ini.j2
It does not support coverage 6 which is needed for Python 3.11.
> Do not use `coverage-python-version` together with Python 3.11.

- config/default/tests.yml.j2
Fixes #145 
Sourced (and fixed) from https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
> Avoid duplicate actions runs in the default GHA template

- config/default/tox-testenv.j2
Some packages testing future Python versions need a RestrictedPython which runs on Python 3.11 so we activated installing pre-released package versions.
Until `repoze.sphinx.autointerface` supports Sphinx 5 we have to use an older version.
Needed by https://github.com/zopefoundation/zope.security/pull/86.
> Fix packages which test future Python versions.

- config/c-code/tests.yml.j2
There is already cffi 1.15.0 installed. Uninstalling it fails because a file seems to be missing.
Updating setuptools beforehand did not help, so I am excluding the new cffi version for now and we'll see what happens on the next release.
Used for https://github.com/zopefoundation/Persistence/pull/32
(Needed for all other c-code packages with pypy2 support.)
> Fix C-code PyPy2 builds on GHA.

- config/c-code/tests.yml.j2
This is needed for https://github.com/zopefoundation/zope.security/pull/87
> Fix building of c-code template for Python 3.10 on MacOS.

- config/c-code/tests.yml.j2
This copies a change from the default template to prevent tests for the pull_request event unless the PR is based on an external fork
> Don't run pull_request and push tests simultaneously

- config/c-code/tests.yml.j2
As @Nephirus wrote on https://github.com/zopefoundation/BTrees/pull/179:
> Current binary wheels use -Ofast optimization option, which (apart from other things) enables flush-to-zero (FTZ) behavior for IEEE-754 subnormals. Unfortunately, FTZ is a global CPU flag, so it affect other running code.
> Disable unsafe math optimizations

- config/c-code/tests.yml.j2
As @Nephirus wrote on https://github.com/zopefoundation/BTrees/pull/179:
> Current binary wheels use -Ofast optimization option, which (apart from other things) enables flush-to-zero (FTZ) behavior for IEEE-754 subnormals. Unfortunately, FTZ is a global CPU flag, so it affect other running code.
Unfortunately -fno-unsafe-math-optimizations does not override -Ofast, so we have to stop using -Ofast instead.
> Disable unsafe math optimizations (try 2)

- config/README.rst
- config/config-package.py
- config/default/gitignore.j2
- config/default/setup.cfg.j2
This needs the ability to add `*.mo` to `.gitignore` and the ability to configure `zest.releaser` to require `zest.pocompile`.
It is used in https://github.com/zopefoundation/zope.app.locales/pull/18.
> Add support for creating *.mo files during the release process.

- config/zope-product/tox.ini.j2
Fixes #56 
This change creates paths to the `test` script using `{envdir}/bin` explicitly instead of `{envbindir}`, which breaks those paths on Windows.
See https://github.com/zopefoundation/DateTime/pull/40/files for a place where I had to fix those paths manually because Windows tests broke.
> Fix path to ``test`` script on Windows

- config/c-code/tests.yml.j2
Tested in https://github.com/zopefoundation/AccessControl/pull/134
> Skip manylinux pr the same way it is done for the other jobs.

- config/c-code/tests-cache.j2
Source https://hynek.me/til/set-output-deprecation-github-actions/
Tested in https://github.com/zopefoundation/Persistence/pull/34
> Fix GHA deprecation warning.

- config/config-package.py
- config/default/appveyor.yml.j2
The next step would be to declare 3.11 as generally supported version instead of being a future version but there is no 3.12 release on GHA, yet.
Used for https://github.com/zopefoundation/ExtensionClass/pull/56
> Add support for Python 3.11 final.

- config/c-code/manylinux-install.sh.j2
- config/c-code/tests-strategy.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/appveyor.yml.j2
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/default/tox-testenv.j2
Make Python 3.12 the new future version.
(Even though the first alpha release is not yet available on GHA.)
Maybe we do not have to merge this PR now, but it is needed for https://github.com/zopefoundation/RestrictedPython/pull/243.
> Declare Python 3.11 als officially supported.

- config/c-code/tests.yml.j2
Taken from https://github.com/zopefoundation/BTrees/pull/186
I have been using this to finish zope.container and zope.security already
> Apply Michael's fix for macOS 3.11

- config/default/appveyor.yml.j2
Not testing 32-bit on Windows also means, we do no longer create 32-bit Windows wheels.
@dataflake Is this the goal you wanted to achieve with #165?
Tested in https://github.com/zopefoundation/ExtensionClass/pull/57.
Fixes #165.
> Drop 32-bit Windows support.

- config/c-code/tests-cache.j2
- config/c-code/tests-download.j2
- config/c-code/tests.yml.j2
- config/default/tests.yml.j2
This will get rid of many deprecation warnings about node versions etc.
> Update actions versions to fix deprecation warnings

- config/zope-product/tox.ini.j2
zc.buildout 3.0.0 was a brown bag release and 3.0.0rc3 doesn't work well with the latest pip/setuptools/etc
> Require at least zc.buildout 3.0.1

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
This works just like `--with-windows` and it allows us to force testing on macOS with packages where it's important, like Zope itself.
> Add a flag to explicitly add testing on macOS test runners

- config/README.rst
- config/c-code/tests.yml.j2
- config/config-package.py
This change applies the same environment flags used by cibuildwheel. Specifically, version 10.9 is explicitly selected when building x86_64 (and universal2) wheels. Only arm64 wheels select version 11.0. See here for details:
https://github.com/pypa/cibuildwheel/blob/2e6cbe2435ef410156319c98625002ed76e08785/cibuildwheel/macos.py#L217-L232
I have tried it on AccessControl master and the wheels get built just fine, see https://github.com/zopefoundation/AccessControl/actions/runs/3445282682/jobs/5748817908
You don't happen to know how to get the equivalent of "python version > 3.10" into a GHA expression, do you? That list of specific versions as condition irks me.
> Enable building x86_64, arm64 and universal2 wheels on supported macOS Python versions

- config/config-package.py
- config/default/tests.yml.j2
- config/default/tox-lint.j2
Used in https://github.com/zopefoundation/zope.copy/pull/9
> Fix GHA: ubuntu-latest no longer contains Python 2.7 up to 3.6.

- config/c-code/tests.yml.j2
Fixes #182 
See test run with `Acquisition` at https://github.com/zopefoundation/Acquisition/actions/runs/3794775048. The logs for the manylinux builds confirm that a Python 3.11 binary egg is built.
> Update manylinux docker images for i686 and x86_64 from 2010 to 2014

- config/config-package.py
A bigger step than #185 but on the same direction.
Move as much code as possible to functions.
This way, one can really see the flow/organization of the code much more clear.
The next step, in a future PR would be to create a class to group together all functions and minimize the global usage of variables, which would make it for a much nicer/easier to follow code base IMHO.
Is that something that would be welcomed? 🤔 🍀
> refactor: turn it into a class

- config/c-code/tox.ini.j2
That way local installs where we have no control over the version of `tox` used can't get too badly out of sync with GitHub Actions installs, which will always grab the latest version.
> Now that Python 2 support is gone we can require tox 4

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
This PR adds an option to set values for the `env` variable in the GHA `Test`step.
> Add option to set environment variables for the GHA test step

- config/README.rst
- config/c-code/tests-strategy.j2
- config/config-package.py
- config/default/setup.cfg.j2
- config/default/tests.yml.j2
That version seems to run more stable, see https://github.com/zopefoundation/zc.catalog/pull/16
Plus fix whitespace in isort config. This never seems to have worked since I implemented it a year ago. Shame on me.
> Upgrade PyPy to 3.9.

- .pre-commit-config.yaml
- config/zope-product/tox.ini.j2
This is needed for zope.sqlachemy.
Used in https://github.com/zopefoundation/zope.sqlalchemy/pull/77
> Inherit the `allowlist_externals` to the coverage env.

- config/default/tests.yml.j2
Python 3.12 seems to need the same treatment like Python 3.11.
Used in https://github.com/zopefoundation/Zope/pull/1103
> Do not run Python 3.12 on MacOS

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
- config/toolkit/packages.txt
- config/toolkit/tox.ini.j2
Will be used for zopetoolkit and groktoolkit.
The previous mentioning of a groktoolkit template was not true, it never made it out of my hard disk into the repository as it was not ready.
Used in https://github.com/zopefoundation/zopetoolkit/pull/57.
> Add toolkit template.

- config/README.rst
- config/config-package.py
- config/default/tox-docs.j2
- config/default/tox-testenv.j2
Used for https://github.com/zopefoundation/zope.hookable/pull/30
> Add ability to set custom docs-dependencies.

- config/c-code/manylinux-install.sh.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/default/tox-testenv.j2
- config/toolkit/tox.ini.j2
- config/zope-product/tox.ini.j2
This PR does two things:
- move Python 3.12 to the list of standard non-future Pythons
- prepare places that want to use future Pythons by using `py313`
- redefine `FUTURE_PYTHON_VERSION` to an empty string
- only render future python-related template items if `FUTURE_PYTHON_VERSION` is not empty
With the last two changes individual packages do not need to turn off their `with-future-python` flag during those times when the Python release is finished and no prerelease exists for the next Python version.
> Switch Python 3.12 to non-future and change with-future-python behavior

- config/README.rst
- config/config-package.py
- config/default/readthedocs.yaml.j2
This adds support for additional lines to be inserted into the `.readthedocs.yaml` build configuration section. This is useful to e.g. install additional packages in the OS.
> Add ability to specify additional RTD build options

- config/config-package.py
This change solves an ongoing annoyance for my own workflow: I always use `--no-commit` because I want to eyeball all changes. But several places use `git add`, which puts the changes into the git staging area and thus out of reach of `git diff`. I always have to do `git restore --staged` for those files. With this change `git add` is not done when `--no-commit` is used.
> Don't call "git add" if the --no-commit flag is set

- config/config-package.py
See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-a-python-version and scroll down to `hyphen ranges`: It's apparently possible to specify a range of versions for a Python version to be used with the GitHub `setup-python` action. That way we won't have to update this package for every new prerelease. It also means testing for the value of `FUTURE_PYTHON_VERSION` to determine if `with_future_python` has to be set is no longer necessary. Only the package's `future-python` setting is considered.
This is not fully tested because there's no Python 3.13 preprelease yet.
> Specify FUTURE_PYTHON_VERSION as version range

- config/README.rst
- config/default/tests.yml.j2
This PR addresses the issues found after merging #216.
- prescribe Python 3.11 for using this package
- fix documentation to rename maccabe to mccabe
- fix documentation wording for flake8 additional-plugins
- add release-check test to GHA steps
> Address issues from PR #216

- config/zope-product/tox.ini.j2
Reverts zopefoundation/meta#157
Reason: In https://github.com/zopefoundation/DateTime/pull/57 windows tests break again and I found another solution there.
> Revert "Fix path to ``test`` script on Windows"

- config/c-code/tests.yml.j2
Used in https://github.com/zopefoundation/persistent/pull/188
> Support Python 3.13a3 by installing not yet released packages.

- config/c-code/tests-cache.j2
- config/default/tests.yml.j2
This prevents deprecation warnings on the Actions output
> Update GitHub cache action to version 4

- config/c-code/tests.yml.j2
It contains the needed fix for Python 3.13.
Needed for https://github.com/zopefoundation/ExtensionClass/pull/71
> Update to twine 5.0.

- config/c-code/tests.yml.j2
It does not work and I spent too much time trying to get it working. So I gave up and decided to wait for a cffi release.
> Drop special handling for not yet released cffi.

- config/c-code/manylinux-install.sh.j2
Fixes #240 
This change prevents attempts to build a package and run tests on it for non-standard interpreters like the Python 3.13 no-GIL build in the manylinux aarch64 environment.
Tested successfully at https://github.com/zopefoundation/zope.interface/actions/runs/9202742557
> Prevent non-standard interpreters in manylinux builds

- config/c-code/tests.yml.j2
A step for uploading the Windows wheels built on GitHub was missing. See https://github.com/zopefoundation/zope.interface/pull/296
> Add an explicit PyPI upload step for Windows

- config/c-code/tests.yml.j2
- config/default/tox-testenv.j2
Pin setuptools so...
- source distributions don't get dotted names replaced by underscores
- zc.buildout compatibility issues
> Pin setuptools again

- config/c-code/tests.yml.j2
The c-code template had a broken linting step that did nothing and wanted to use pylint. Switch to using tox instead so the linting with tox locally and the linting on GHA deliver the same results.
> Lint using tox

- config/default/tests.yml.j2
Workaround for the many problems with the universal2-based macOS GHA runner Python builds like #181 
With this change the default GHA test configuration uses a custom "Test" step for macOS runners that is hardcoded to call the respective tox environment and tacking on an environment marker. The tox configuration for each package can then react to that marker and e.g. pre-install dependencies like C-code wheels that zc.buildout cannot install itself.
Used/tested with Zope (https://github.com/zopefoundation/Zope/pull/1214)
> Use custom test step for macOS

- config/c-code/tests.yml.j2
- config/set_branch_protection_rules.py
... and fix the macOS version for Python 3.8 tests branch protection rule.
> Use new cffi prerelease

- config/config-package.py
This change overrides the value for `with_future_python` and sets it to `false` if there is no future Python version defined.
The goal is to "turn off" the flag with just a change in meta/config itself instead of having to touch all package configurations. So when a new Python version is released and no suitable next Python alpha/beta is available on GHA all you need to do is to set `shared.packages.FUTURE_PYTHON_VERSION` to an empty string and add the new Python release version to the various templates before re-running for a given package. The package won't need any changes itself. Once a new alpha/beta is on GHA that version number can be set again and the packages that do define `with_future_python` will pick it up the next time meta/config is run on them.
> Set with_future_python to false if no future python version is defined

- config/drop-legacy-python.py
Removed the Python 2 specific parts as this is already done for all supported repositories.
This is not perfect yet, but a step towards making it usable again.
Used for https://github.com/zopefoundation/zope.configuration/pull/62
> Rework drop-legacy python script to be usable for 3.7.

- config/README.rst
- config/default/tox-lint.j2
- config/shared/packages.py
- config/update-python-support.py
Remove previous script to drop support for old Python versions instead.
The script is now able to drop and add in one go and does not need to be adapted for version updates in the range of supported versions.
See https://github.com/zopefoundation/z3c.currency/pull/8 which was built using this PR.
> Add script to update to currently supported Python versions.

- config/default/tox-testenv.j2
> fix: disable 'usedevelop' when testing projects with C extensions

- config/buildout-recipe/coveragerc.j2
- config/buildout-recipe/tox.ini.j2
- config/c-code/coveragerc.j2
- config/c-code/manylinux-install.sh.j2
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/MANIFEST.in.j2
- config/default/gitignore.j2
- config/default/readthedocs.yaml.j2
- config/default/setup.cfg.j2
- config/default/tests.yml.j2
- config/default/tox-lint.j2
- config/pure-python/tox.ini.j2
- config/toolkit/tox.ini.j2
- config/zope-product/tox.ini.j2
(Adjusting to feedback on PR #259).
Use consistent prefix indicating the section of the config containing the option.
- 'fail_under' -> 'coverage_fail_under'
- 'additional_flake8_config' -> 'flake8_additional_config'
- 'additional_check_manifest_ignores' -> 'check_manifest_additional_ignores'
- 'ignore' -> 'git_ignore'
- 'build_extra' -> 'rtd_build_extra'
- 'run_additional_config' -> 'coverage_run_additional_config'
- 'setup' -> 'manylinux_install_setup'
- 'aarch64_tests' -> 'manylinux_aarch64_tests'
- 'use_flake8' -> 'tox_use_flake8'
- 'services' -> 'gha_services'
- 'additional_config' -> 'gha_additional_config'
- 'additional_exclude' -> 'gha_additional_exclude'
- 'steps_before_checkout' -> 'gha_steps_before_checkout'
- 'additional_install' -> 'gha_additional_install'
- …
> chore: rationalize config option names

- config/README.rst
- config/config-package.py
- config/default/setup.cfg.j2
FBO the forked stdlib modules in 'zodbpickle':  we want to keep the diff minimal between the original version and our fork, and so need to disable most kinds of linting entirely for them.
> feat: add 'isort_additional_config' option

- config/c-code/tests.yml.j2
The first attempt at code to delete wheels for unreleased Python versions made the `manylinux` step fail because the files in the wheelhouse folder are owned by root. Using sudo fixes that. I added a `ls` before and after for diagnostic purposes. Now I can see this works.
> Wheel deletion required sudo, the files are owned by root.

- .github/workflows/pre-commit-update.yml
- .pre-commit-config.yaml
- config/README.rst
- config/config-package.py
- config/default/pre-commit-config.yaml.j2
Used for https://github.com/zopefoundation/Zope/pull/1226
> Add teyit for better unittest assertions.

- config/c-code/tests.yml.j2
The `-U` switch will trample over all pins set on the preceding `pip` invocations, in particular the `setuptools` pinned install.
Background: https://github.com/zopefoundation/persistent/actions/runs/10592041991; the just-released `setuptools` 74 seems to cause breakage in `cffi` 1.17 on Windows.
> Prevent force-upgrade during test requirement install

- config/default/tox-testenv.j2
- config/toolkit/tox.ini.j2
- config/zope-product/tox.ini.j2
This PR adds a new tox environment `setuptools-latest` that is not run by default and that inherits everything from the base testenv but overrides the dependencies to pull setuptools straight from the main branch on GitHub.
I tested it against Zope itself and `persistent` and nothing fails (yet), so other than eyeballing what ends up in the tox environment's site-packages I can't prove that it really helps. Yet.
> Add a tox environment that uses setuptools development code

- config/README.rst
- config/config-package.py
This PR is an alternative implementation of #270. It uses `tomlkit` to load an existing file and then merges some sane defaults before writing it to disk.
Successfully tested against Zope, which has no pre-existing `pyproject.toml`, and `BTrees`, which does.
@dwt: Can you check to see if this works for you and gets rid of the warnings?
> Add ``pyproject.toml`` to the list of managed files

- config/c-code/manylinux-install.sh.j2
- config/c-code/tests-cache.j2
- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/default/tox-testenv.j2
- config/requirements.txt
- config/shared/packages.py
- config/toolkit/tox.ini.j2
- config/update-python-support.py
- config/zope-product/tox.ini.j2
This PR moves Python 3.13 into the list of normally tested and compatible Python versions and ends its status as future Python. Since 3.13.0.rc1 it is ABI-stable and there won't be any surprises, so we can start declaring full support where possible. I want to start doing the binary packages.
> Move Python 3.13 into the stable Python category and call a notional Python 3.14 "future Python"

- config/default/tox-testenv.j2
Because it breaks packages that have a
test-additional = ["setenv =", ...]
in their .meta.toml, like zope.publisher.
> Avoid generating an empty setenv =

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/config_package.py
- src/zope/meta/set_branch_protection_rules.py
- src/zope/meta/shared/packages.py
- src/zope/meta/update_python_support.py
This PR adds support for a new command line parameter `--oldest-python` and a corresponding value in `.meta.toml` that allows setting a minimum supported Python version that may be different from the previously hardcoded default.
> Support for specifying a minimum supported Python version

- .meta.toml
- pyproject.toml
- src/zope/meta/set_branch_protection_rules.py
- tox.ini
It has to to start with `py` like `NEWEST_PYTHON`.
Used in https://github.com/zopefoundation/zc.recipe.testrunner/pull/18
> Fix branch protection min version.

- .github/workflows/tests.yml
- .meta.toml
- .pre-commit-config.yaml
- CHANGES.rst
- docs/narr.rst
- setup.py
- src/zope/meta/c-code/tests.yml.j2
- src/zope/meta/shared/packages.py
- tox.ini
This PR sets Python 3.9 as the oldest supported Python version and it removes Python 3.8 support from this package as well.
- Python 3.8 has been EOL for more than two months, see https://devguide.python.org/versions/
- The upcoming Plone 6.1 sets an even higher minimum supported version (3.10)
- zc.buildout really wants to drop it as well, see https://github.com/buildout/buildout/pull/671
- In Zope the list of custom version pins to keep Python 3.8 support gets longer and longer, this is an unnecessary maintenance burden.
> Retire Python 3.8

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/config_package.py
This is needed when this configuration is defined in `pyproject.toml` as there it needs to be a list of strings.
Removed unused config variables for `tox.ini`.
This is needed for https://github.com/zopefoundation/zdaemon/pull/37
> Add `omit` option to `coverage-run` configuration.

- .github/workflows/tests.yml
- .meta.toml
- src/zope/meta/default/tests.yml.j2
Fixes #289.
It does not plainly use the things suggested in the blog post referenced in #289 but the successor provided by uv itself.
Used:
* here in this PR
* https://github.com/zopefoundation/zope.annotation/pull/27
* https://github.com/zopefoundation/zope.exceptions/pull/38
* https://github.com/zopefoundation/zope.testing/pull/50
Sorry for the noise in some of the PRs, they were just not up to date. Maybe we need something here to keep packages automatically up to date.
> Use uv in GitHub Actions.

- src/zope/meta/tests/test_update_python_support.py
- src/zope/meta/update_python_support.py
* Add ability to test against future python versions.
* Fix handling of custom tox envs.
Used for https://github.com/zopefoundation/zope.proxy/pull/74
> Improve update_python_support.py:

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/config_package.py
- src/zope/meta/default/pre-commit-config.yaml.j2
Used in https://github.com/zopefoundation/zope.proxy/pull/74
> Add `pyupgrade-exclude` to `[pre-commit]` section in `.meta.toml`.

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/c-code/tests.yml.j2
- src/zope/meta/c-code/tox.ini.j2
- src/zope/meta/config_package.py
- src/zope/meta/default/tox-release-check.j2
- src/zope/meta/shared/packages.py
The `c-code` tox template was missing the `release-check` step, even though it was defined in the template. Also, the check was never run on GHA.
Noticed it today working on `persistent` where the `release-check` step fails because it wasn't tested as part of `tox -pauto` and the GHA configuration never tested it, either.
This PR also works around wheel name change issues with the latest setuptools/pip and improves formatting for the generated ``pyproject.toml`` file.
It also retires the configuration variables ``require-cffi`` in the ``[c-code]`` section and ``additional-build-dependencies`` in the ``[github-actions]`` section. Packages required for building a package (meaning installed before setup.py is run) should go into pyproject.toml's ``requires`` list in the ``[build-system]`` …
> Add release-check step for c-code templates (and more)

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/config_package.py
When testing configuration changes or when making code changes to `zope.meta` itself the automatic unit test runs are a huge time drain. This PR adds a flag to skip them.
> Add argument ``--no-tests`` to configuration script to skip unit tests

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/buildout-recipe/pyproject_defaults.toml.j2
- src/zope/meta/c-code/pyproject_defaults.toml.j2
- src/zope/meta/config_package.py
- src/zope/meta/default/pyproject_defaults.toml.j2
- src/zope/meta/shared/packages.py
The new argument takes a filesystem path that will be searched for the configuration type folders (and the `default` folder) before the built-in folders are searched for the template files. This allows overriding the built-in templates. I am using it to make using the package configuration script easier for my own and client repositories.
> Add argument ``--template-overrides`` to enable template overrides

- CHANGES.rst
- docs/narr.rst
- src/zope/meta/c-code/tox.ini.j2
- src/zope/meta/config_package.py
- src/zope/meta/default/MANIFEST.in.j2
- src/zope/meta/default/tests.yml.j2
If you specify the `--template-overrides` option to have the `config-package` script look for template files in a custom location this PR lets you omit output files by simply putting an empty template into your template overrides path.
Rationale: I would like to use `zope.meta` to configure non-public repositories that do not need things like a `CONTRIBUTING.md` or a RTD configuration in `.readthedocs.yaml`.
> Add ability to omit creating some optional files

- CHANGES.rst
- src/zope/meta/pep_420.py
- src/zope/meta/update_python_support.py
This script improves the PEP 420 change script:
- actually respect the `--branch` flag
- don't execute the code checking `__init__.py` files in the loop that iterates over every line in `setup.py`
- shorten the change log message because...
- a warning that is addressed to the package maintainer does not belong in a change log
- the `zest.releaser` script `addchangelogentry` does not accept any formatting so you end up with a super-long line there
- add a new flag `--no-tests`, analogous to the same flag for the `config-package` script, that avoids running the tests. Most of the time those will produce a ton of irrelevant output during their first run and they take a long time to run.
In addition, improved the `update-python-support` script:
- support the `--no-tests` flag and pass that …
> Fix several issues in the PEP 420 switching script

- src/zope/meta/buildout-recipe/tox.ini.j2
It installed setuptools >= 80 which currently completely breaks with zc.buildout, so let's pin it here, too.
Used for https://github.com/zopefoundation/z3c.recipe.mkdir/pull/13
> Prevent setuptools problems in buildout template -> coverage

- src/zope/meta/c-code/pyproject_defaults.toml.j2
- src/zope/meta/c-code/tests.yml.j2
Used for https://github.com/zopefoundation/zope.i18nmessageid/pull/65
Reason of the changes:
* Some c-code packages could not be built successfully on pypy-windows because `setuptools == 78.1.1` could not be found. The list of known `setuptools` versions ends at 76.0.0 Source: https://github.com/zopefoundation/zope.i18nmessageid/actions/runs/17316990877/job/49161644379
* I tried to install `setuptools==78.1.1` beforehand, and found out that it is already there but the `pip install .[test]` command complains that it cannot see it. Source: https://github.com/zopefoundation/zope.i18nmessageid/actions/runs/17370121781/job/49303957516
* Even putting the installation of `setuptools` and `.[test]` into the same pip call did not help. Source: …
> Make windows pypy runs in c-code successful again.
