zopefoundation/meta

- .gitignore
> Ignore lib64 symlink

- config/pure-python/travis.yml
... as with 3.10 this would break anyway.
> Quote Python version numbers

- config/README.rst
- config/config-package.py
- config/default/setup.cfg.j2
It allows to ignore additional files from check-manifest.
> Add additional-check-manifest-ignores.

- config/README.rst
- config/config-package.py
- config/default/setup.cfg.j2
- config/pure-python/packages.txt
This is needed for https://github.com/zopefoundation/grokcore.chameleon/pull/3
> Allow to ignore bad ideas in check-manifest.

- config/README.rst
- config/config-package.py
- config/pure-python/packages.txt
- config/pure-python/tox.ini.j2
Needed for https://github.com/zopefoundation/refline.srccheck/pull/2
> Add ability to configure coverage:run options.

- config/README.rst
- config/config-package.py
- config/default/MANIFEST.in.j2
- config/default/appveyor.yml.j2
- config/default/tests.yml.j2
Used in https://github.com/zopefoundation/zope.sendmail/pull/37
Maybe we'll switch to GHA for Windows in the future but for now I just wanted to keep the status quo.
> Add ability to create appveyor.yml.

- config/README.rst
- config/config-package.py
- config/default/tox-testenv.j2
This is needed for https://github.com/zopefoundation/zope.publisher/pull/58/commits/a897f45ee32214bc09d2d1bdedb75edb97d67de5
> Add ability to configure [testenv] in tox.ini.

- config/README.rst
- config/config-package.py
- config/default/tests.yml.j2
This is needed for https://github.com/zopefoundation/zope.sqlalchemy/pull/56
> Add services for buildout projects.

- config/README.rst
- config/config-package.py
- config/default/appveyor.yml.j2
- config/default/gitignore
- config/default/setup.cfg.j2
- config/default/tox-docs.j2
- config/zope-product/packages.txt
- config/zope-product/tox.ini.j2
Plus some fixes found while porting Zope.
Used to create https://github.com/zopefoundation/Zope/pull/942.
> Configure isort and appveyor.

- config/README.rst
- config/config-package.py
- config/default/tox-lint.j2
- config/zope-product/tox.ini.j2
This in needed for https://github.com/zopefoundation/zope.app.locales/pull/13.
> Add the ability to flake8 additional files or directories.

- config/README.rst
- config/buildout-recipe/coveragerc.j2
- config/buildout-recipe/tox.ini.j2
- config/config-package.py
- config/pure-python/tox.ini.j2
- config/zope-product/tox.ini.j2
It is needed for https://github.com/zopefoundation/zdaemon/pull/25.
> Add ability to configure [testenv:coverage] setenv.

- config/README.rst
- config/config-package.py
- config/default/appveyor.yml.j2
Additional Appveyor environment configuration options
Needed for https://github.com/zopefoundation/zope.testrunner/pull/116.
> Appveyor environment config

- .github/workflows/pre-commit.yml
- .isort.cfg
- .pre-commit-config.yaml
- config/config-package.py
- config/meta-cfg-to-toml.py
- config/multi-call.py
There have been some flake8 errors and superfluous imports in this package, so it might be a good idea to ensure this also here.
> Add linting for this repo.

- config/README.rst
- config/config-package.py
- config/default/setup.cfg.j2
- config/default/tests.yml.j2
- config/zope-product/tox.ini.j2
Plus some other fixed needed for https://github.com/zopefoundation/zope.sqlalchemy/pull/62 resp. fixed while working on that PR.
> Add support for GHA test-commands

- config/default/tox-testenv.j2
- config/pure-python/tox.ini.j2
Needed for 
* https://github.com/zopefoundation/zope.dublincore/pull/16
* https://github.com/zopefoundation/transaction/pull/102
> Pin `Sphinx < 4` in additional places.

- config/README.rst
- config/config-package.py
Fixes #82.
https://github.com/zopefoundation/zc.sourcefactory/pull/8 was created using this branch.
> Add ability to specify a custom commit message.

- config/c-code/appveyor-publish.j2
- config/c-code/manylinux-install.sh.j2
- config/c-code/manylinux.sh
- config/c-code/packages.txt
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/appveyor-publish.j2
- config/default/appveyor.yml.j2
- config/default/gitignore
Adapt the version used for `zope.interface` to be usable in `ExtensionClass`.
Needed for https://github.com/zopefoundation/ExtensionClass/pull/29
> Improve C-code template

- config/default/setup.cfg.j2
> Do not create wheels locally, it has to be done by GHA.

- config/config-package.py
See https://github.com/zopefoundation/meta/issues/97#issuecomment-862234270
> Allow python .../config-package.py .

- config/c-code/packages.txt
- config/c-code/tests.yml.j2
Needed for https://github.com/zopefoundation/zodbpickle/pull/63
> Allow to customize the test commands for GHA when using type c-code.

- config/README.rst
- config/c-code/tests-strategy.j2
- config/config-package.py
- config/default/tests.yml.j2
Used for https://github.com/zopefoundation/ZODB/pull/357.
> Add ability to manually exclude entries from the GHA matrix.

- config/README.rst
- config/c-code/manylinux-install.sh.j2
- config/config-package.py
This will be needed for BTrees.
> Add ability to configure the setup for manylinux-install.sh.

- config/README.rst
- config/config-package.py
- config/default/tox-lint.j2
- config/zope-product/tox.ini.j2
This PR is needed for https://github.com/zopefoundation/RestrictedPython/pull/234.
> Allow to add additional sources for isort.

- config/README.rst
- config/c-code/manylinux-install.sh.j2
- config/c-code/tests-strategy.j2
- config/c-code/tests.yml.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/appveyor.yml.j2
- config/default/tests.yml.j2
- config/default/tox-envlist.j2
- config/default/tox-testenv.j2
- config/requirements.txt
- config/zope-product/tox.ini.j2
See https://github.com/zopefoundation/meta/issues/177
Used in https://github.com/zopefoundation/zope.testing/pull/45
> Drop support for Python 2.7 up to 3.6.

- .github/workflows/pre-commit.yml
- config/README.rst
- config/buildout-recipe/coveragerc.j2
- config/buildout-recipe/tox.ini.j2
- config/c-code/manylinux-install.sh.j2
- config/c-code/tests-strategy.j2
- config/c-code/tox.ini.j2
- config/config-package.py
- config/default/appveyor.yml.j2
- config/default/setup.cfg.j2
- config/default/tests.yml.j2
- config/default/tox-coverage-config.j2
- config/default/tox-envlist.j2
- config/drop-legacy-python.py
- config/meta-cfg-to-toml.py
- config/pure-python/tox.ini.j2
- config/requirements.txt
- config/shared/call.py
- config/shared/git.py
- config/zope-product/tox.ini.j2
Used to create:
* https://github.com/zopefoundation/zope.testbrowser/pull/100
> Add script to drop Python 2.7 up to 3.6 support.

- config/README.rst
- config/multi-call.py
This way changes are not lost 🤞🏾 🍀
> Stash local changes

- config/config-package.py
I'm having a look at the code and I saw a pattern repeated, so I though it can be simplified a little bit, to make it a bit more readable 🍀
> Simplify option handling

- config/README.rst
- config/c-code/tests.yml.j2
- config/config-package.py
Used for https://github.com/zopefoundation/persistent/pull/196
> Add an option to require installing cffi.

- config/set_branch_protection_rules.py
Used for https://github.com/zopefoundation/Zope/pull/1222
> Require successful MacOS tests if tests are run there.

- .meta.toml
- docs/narr.rst
- **Configuring for pure-python**
- **Update Python version support.**
> Drop support for Python 3.8.

- .github/workflows/pre-commit.yml
- .github/workflows/tests.yml
- .meta.toml
- src/zope/meta/default/pre-commit.yml.j2
- src/zope/meta/default/tests.yml.j2
See https://github.com/zopefoundation/RestrictedPython/security/code-scanning
Tried out in https://github.com/zopefoundation/RestrictedPython/pull/296
> Secure workflows as suggested by Code scanning alerts of RestrictedPython.

- .meta.toml
- CHANGES.rst
- setup.py
- src/zope/meta/config_package.py
This is needed to match current best practices.
Fixes #288.
> Update `setup.py` of configured packages with small textual changes.

- .meta.toml
- .pre-commit-config.yaml
- src/zope/meta/default/pre-commit-config.yaml.j2
Change log: https://github.com/PyCQA/isort/releases/tag/6.0.0
> Update to newest isort version in pre-commit config.

- .github/workflows/pre-commit-update.yml
- .github/workflows/pre-commit.yml
- .github/workflows/tests.yml
- .meta.toml
- src/zope/meta/c-code/tests-cache.j2
- src/zope/meta/default/pre-commit.yml.j2
- src/zope/meta/default/tests.yml.j2
> Update checkout action to version 5

- .meta.toml
- CHANGES.rst
- setup.py
- src/zope/__init__.py
- src/zope/meta/pure-python/packages.txt
- **Bumped version for breaking release.**
- **Replace ``pkg_resources`` namespace with PEP 420 native namespace.**
- **Switch to PEP 420 native namespace.**
> Switch to PEP 420 native namespace.
